version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jobportal  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: Uday@2215302  
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5455:5432"  

  web:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_DB: jobportal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Uday@2215302
      POSTGRES_HOST: db  
      POSTGRES_PORT: 5432  
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media  
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "onlinejobportal.wsgi:application"]

volumes:
  pg_data:
  media_data:  
